import pandas as pd

df = pd.read_csv("2023.04.05-13.34.10.csv")
to_drop = ['Power Status', 'Public IP Address', 'Operation State', 'Controller Torque Output', 'Heartbeat', 'System Health',
           'Mode', 'Control Type', 'Current Torque', 'Current Orientation', 'Target Orientation', 'Rotational Speed', 'Battery Charge Percentage',
           'Motor Temp', 'Loadmass', 'Controller Version', 'Controller Branch', 'Controller Commit Time', 'Controller Build Time',
           'Controller Current Firmware', 'Control System Status', 'Services Alive Status', 'Hardware Init Status', 'Devices Init Status', 'Services Init Status', 'Regen. Current Max',
           'Regen. Torque Max', 'Drain Current Max', 'Drain Torque Max', 'Relay Status Flags', 'Motor Torque Demand', 'Motor Enable Demand', 
           'Motor ASC Demand', 'Motor Ramp Demand', 'Hook Status', 'Error ID', 'GUID Request', 'Motion Command Request', 'Flags Request', 
           'Orientation Change Request', 'Speed Request', 'Request Status', 'Command Response Status', 'Command Response Value', 'Orientation Controls Enabled Status',
           'Orientation Controls Max Speed Status', 'Orientation Controls Slowdown Speed Status', 'Orientation Controls Start Angle Status', 'Orientation Slowdown Finish Angle Status',
           'Load Cell Reading A Status', 'Load Cell Actual Weight A Status', 'Load Cell Reading B Status',
           'Load Cell Actual Weight B Status', 'Load Cell Reading C Status', 'Load Cell Actual Weight C Status',
           'Load Cell Reading D Status', 'Load Cell Actual Weight D Status', 'Battery Capacity Status',
           'Battery Max Regen Current Status', 'Battery Max Drain Current Status', 'Battery Regen Upper Bound Status',
           'Battery Regen Lower Bound Status', 'Battery Drain Upper Bound Status', 'Battery Drain Lower Bound Status',
           'Battery Low SOC Warning Status', 'Battery Low SOC Warning Clear Status', 'Battery Low Cell Voltage Warning Status',
           'Control Rotate Freely Speed Gain Status', 'Control Rotate Freely Torque Max Status', 'Control Heading Gain Status',
           'Control Speed Gain Status', 'Control Speed Slow Status', 'Control Speed Max Status',
           'Motor Torque Max Status', 'Motor Speed Max Status', 'Gearbox Ratio Status',
           'Unit WLL Mass Status', 'Unit Tare Mass Status', 'Unit On Ground Mass Ratio Status',
           'Horn Loudness Status', 'Control Rotate Freely Low Threshold', 'Control Rotate Freely High Threshold',
           'Torque Override Enabled Status', 'Orientation Controls Enabled Value', 'Orientation Controls Max Speed Value',
           'Orientation Controls Slowdown Speed Value', 'Orientation Controls Start Angle Value', 'Orientation Slowdown Finish Angle Value',
           'get_load_cell_reading_a_value', 'get_load_cell_actual_weight_a_value', 'get_load_cell_reading_b_value',
           'get_load_cell_actual_weight_b_value', 'get_load_cell_reading_c_value', 'get_load_cell_actual_weight_c_value',
           'get_load_cell_reading_d_value', 'get_load_cell_actual_weight_d_value', 'get_battery_capacity_value',
            'get_battery_max_regen_current_value', 'get_battery_max_drain_current_value', 'get_battery_regen_upper_bound_value',
            'get_battery_regen_lower_bound_value', 'get_battery_drain_upper_bound_value', 'get_battery_drain_lower_bound_value',
            'get_battery_low_soc_warning_value', 'get_battery_low_soc_warning_clear_value', 'get_battery_low_cell_voltage_warning_value',
            'get_control_rotate_freely_speed_gain_value', 'get_control_rotate_freely_torque_max_value', 'get_control_heading_gain_value',
            'get_control_speed_gain_value', 'get_control_speed_slow_value', 'get_control_speed_max_value','get_motor_torque_max_value',
            'get_motor_speed_max_value', 'get_gearbox_ratio_value', 'get_unit_wll_mass_value', 'get_unit_tare_mass_value',
            'get_unit_on_ground_mass_ratio_value', 'get_horn_loudness_value', 'get_control_rotate_freely_low_threshold_value',
            'get_control_rotate_freely_high_threshold_value', 'get_torque_override_enabled_value', 'Charger Voltage',
            'Charger Current', 'Charger Enabled', 'Protean Torque Mirro', 'Protean Torque Limit Cause',
            'Protean Fault ID', 'Protean Demand Achievable', 'Protean Demand Plausible', 'Protean Positive Torque Limit',
            'Protean Negative Torque Limit', 'Protean Motor Speed', 'Protean Torque Estimate', 'Protean Enable State', 'Protean ASC State',
            'Protean Motor Ready', 'Protean Fault Level', 'Protean Disabled Drag Torque', 'Protean Torque Ramp Demand',
            'Protean HV Bus Voltage', 'Protean HV Bus Current', 'Protean IGBT Temperature', 'Protean Coil Temperature',
            'Protean Zero Current Torque', 'Protean Speed Maximum', 'Protean Power Board Temperature',
            'Protean Stator Temperature', 'Protean Control Board Temperature', 'Protean Receiving VCU Demands',
            'Protean Receiving DCS Demands', 'Sevcon Torque Target', 'Sevcon Torque Actual',
            'Sevcon Motor Current', 'Sevcon Motor Voltage', 'Sevcon Status', 'Sevcon Fault',
            'Sevcon Motor Temperature', 'Sevcon Motor Speed', 'Sevcon Max Speed', 'Sevcon Battery Voltage',
            'Sevcon Battery Current', 'Sevcon Max Torque', 'Sevcon Motor Id', 'Sevcon Motor Iq', 'Sevcon Motor Ud',
            'Sevcon Motor Uq', '24V Regulator Voltage', 'GPS Date Time', 'GPS Location',
            'Pressure', 'Reference Pressure', 'Addio Fan Current', 'Addio Horn Current', 'Teleradio Buttons', 
            'Teleradio Button 1 State', 'Teleradio Button 2 State', 'Teleradio Button 3 State', 'Teleradio Button 4 State',
            'Teleradio Button 5 State', 'Teleradio Button 6 State', 'Teleradio Button 7 State', 'Teleradio Button 8 State',
            'Teleradio Button Start Left State', 'Teleradio Button Start Right State', 'Teleradio Battery Level',
            'Teleradio Charge Status', 'Teleradio Lost Feedback', 'Teleradio Relay Status', 'Teleradio Active Radio Channel',
            'Teleradio RSSI', 'Teleradio Rx Inputs', 'Teleradio Stop Relays Active', 'Teleradio Radio Link Up', 'Teleradio Tx Session Active',
            'Teleradio Tx Zero Position Acquired', 'Teleradio Cable Control Active', 'Teleradio E-Stop Button State', 'Local E-Stop Active',
            'Remote Stop Active', 'Watchdog Stop Active', 'Standby Mode Active', 'Safety Relay 1 Active', 'Safety Relay 2 Active',
            'Safety Relays Okay', 'RTC Relay Active', 'Command', 'Flags', 'Orientation Change',
            'Speed', 'Message ID', 'WebSocket Server Status']
df.drop(to_drop, inplace = True, axis = 1)

df.dropna(subset=df.columns, how='all', inplace=True)

print(df.head())
